/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.quickj.utils.freeimage4j;

public final class FREE_IMAGE_FILTER {
  public final static int FILTER_BOX = 0;
  public final static int FILTER_BICUBIC = 1;
  public final static int FILTER_BILINEAR = 2;
  public final static int FILTER_BSPLINE = 3;
  public final static int FILTER_CATMULLROM = 4;
  public final static int FILTER_LANCZOS3 = 5;
}

