/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.quickj.utils.freeimage4j;

public final class FREE_IMAGE_DITHER {
  public final static int FID_FS = 0;
  public final static int FID_BAYER4x4 = 1;
  public final static int FID_BAYER8x8 = 2;
  public final static int FID_CLUSTER6x6 = 3;
  public final static int FID_CLUSTER8x8 = 4;
  public final static int FID_CLUSTER16x16 = 5;
  public final static int FID_BAYER16x16 = 6;
}

