/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.quickj.utils.freeimage4j;

public final class FREE_IMAGE_QUANTIZE {
  public final static int FIQ_WUQUANT = 0;
  public final static int FIQ_NNQUANT = 1;
}

