/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package cn.quickj.utils.freeimage4j;

public final class FREE_IMAGE_FORMAT {
  public final static int FIF_UNKNOWN = -1;
  public final static int FIF_BMP = 0;
  public final static int FIF_ICO = 1;
  public final static int FIF_JPEG = 2;
  public final static int FIF_JNG = 3;
  public final static int FIF_KOALA = 4;
  public final static int FIF_LBM = 5;
  public final static int FIF_IFF = FIF_LBM;
  public final static int FIF_MNG = 6;
  public final static int FIF_PBM = 7;
  public final static int FIF_PBMRAW = 8;
  public final static int FIF_PCD = 9;
  public final static int FIF_PCX = 10;
  public final static int FIF_PGM = 11;
  public final static int FIF_PGMRAW = 12;
  public final static int FIF_PNG = 13;
  public final static int FIF_PPM = 14;
  public final static int FIF_PPMRAW = 15;
  public final static int FIF_RAS = 16;
  public final static int FIF_TARGA = 17;
  public final static int FIF_TIFF = 18;
  public final static int FIF_WBMP = 19;
  public final static int FIF_PSD = 20;
  public final static int FIF_CUT = 21;
  public final static int FIF_XBM = 22;
  public final static int FIF_XPM = 23;
  public final static int FIF_DDS = 24;
  public final static int FIF_GIF = 25;
  public final static int FIF_HDR = 26;
  public final static int FIF_FAXG3 = 27;
  public final static int FIF_SGI = 28;
  public final static int FIF_EXR = 29;
  public final static int FIF_J2K = 30;
  public final static int FIF_JP2 = 31;
}

